version: '3.4'

services:
  cda.api:
    image: ${DOCKER_REGISTRY-}cdaapi
    build:
      context: .
      dockerfile: CDA.API/Dockerfile
    networks:
      - my-new-network
    ports:
      - "8081:8081"

  my-redis:
    image: redis
    networks:
      - my-new-network
    ports:
      - "6379:6379"

networks:
  my-new-network:
    driver: bridge