version: '3.4'

services:
  cda.api:
    image: ${DOCKER_REGISTRY-}cdaapi
    build:
      context: .
      dockerfile: CDA.API/Dockerfile
    networks:
      - my-network

  my-redis:
    image: redis
    networks:
      - my-network
    ports:
      - "6379:6379"

networks:
  my-network:
    external: true